services:
  oracle:
    # Always use fqdn *and* digest for determinism
    image: ghcr.io/flashbackai/flashback-encryption:1.0
    platform: linux/amd64
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - RPC_URL=${RPC_URL}
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock   # mandatory for enclave agent
